### ISSUE TITLE
Thank you for this ansible role and some minor suggestion(?)

### ISSUE THREAD

**Issue by wdlingit** [scicore-unibas-ch/ansible-role-slurm#1]
I used this role with some minor modification and it works well in my ubuntu cluster. Just a few minor comments:

1. control machine and slurmdbd are separated and AccountingStorageHost={{ slurm_master_host }} in slurm.conf.j2
2. after modifying AccountingStorageHost={{ slurm_master_host }} to AccountingStorageHost={{ slurm_dbd_host }}, there were some error message on dbd port. So I tried setting AccountingStoragePort=6819 in slurm.conf.j2 and DbdPort=6819 in slurmdbd.conf.j2

**Comment by pescobar** [comment]
Thanks for reporting these issues.

I have published a new version `0.0.6` to ansible galaxy with your suggestions.
