### ISSUE TITLE
slurm_user is not a dict anymore 

### ISSUE THREAD

**Issue by fikipollo** [scicore-unibas-ch/ansible-role-slurm#10]
Hi there

Thanks for this awesome role.

I've detected an issue when deploying the slurm.conf file using the default template in **Ubuntu** branch.

The variable `slurm_user` is not longer a dict so the following line fails when filling the template (templates/slurm.conf.j2).

```
SlurmUser={{ slurm_user[ansible_os_family] }}
```

https://github.com/scicore-unibas-ch/ansible-role-slurm/blob/9e9af501a1a692358d27023568c1607173d154c5/templates/slurm.conf.j2#L153C1-L154C1

All the best

**Comment by pescobar** [comment]
thanks for reporting the issue. I missed this one when removing the redhat family support. 

I have fixed it in the ubuntu branch
